// Project catalogue for Architects Accord — Ar. Prabhjot Bhandari
window.AA_PROJECTS = [
  {
    id: "p01",
    code: "AA-2401",
    title: "4 BHK Residential Villa",
    type: "Residential",
    subType: "Residential Architecture",
    locality: "Sector 91, Mohali",
    plotSize: "500 Sq. Yd.",
    builtUp: "5,400 Sq. Ft.",
    bedrooms: 4,
    bathrooms: 5,
    facing: "North-East",
    parking: 3,
    furnishing: "Full Turnkey",
    age: "Completed 2023",
    floor: "G + 2",
    status: "Delivered",
    price: "Architecture + Interiors",
    pricePerSqft: "Complete Turnkey",
    listingDate: "12 Apr 2023",
    rera: "AA-RES-2401",
    tags: ["Turnkey", "Custom Interiors", "Landscape"],
    summary:
      "A monolithic stone-clad villa on a quiet park-facing plot. Triple-height foyer, oak floors, modular kitchen, and a screened rear lawn — designed and delivered end-to-end.",
    detail:
      "Designed for a family of five on a 500 sq. yd. corner plot. The brief called for generous entertaining spaces, four private bedroom suites, and a home that reads warm despite its architectural scale. Ground floor opens through a 12-ft pivot door into a triple-height foyer with travertine inlay. Drawing and dining are split by a low-profile gas fireplace. Kitchen is full modular with integrated appliances and a walk-in pantry. Master suite on first floor has its own balcony over the park. Interior design, custom joinery, and landscape were all delivered by Architects Accord.",
    hero: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Custom modular kitchen", "Home automation", "Landscape design", "Custom joinery", "CCTV & security", "Lift shaft"],
  },
  {
    id: "p02",
    code: "AA-2402",
    title: "Commercial Office Fit-out",
    type: "Commercial",
    subType: "Commercial Architecture",
    locality: "Sector 70, Mohali",
    plotSize: "250 Sq. Yd.",
    builtUp: "3,600 Sq. Ft.",
    bedrooms: null,
    bathrooms: 4,
    facing: "South",
    parking: "Front + rear",
    furnishing: "Full Fit-out",
    age: "Completed 2024",
    floor: "G + 3",
    status: "Delivered",
    price: "Architecture + Fit-out",
    pricePerSqft: "Commercial Grade",
    listingDate: "21 Mar 2024",
    rera: "AA-COM-2402",
    tags: ["Office", "Main Road", "Full Fit-out"],
    summary:
      "A four-storey commercial building on the main 100-ft road. Architecture, interiors, and complete fit-out designed and delivered by Architects Accord.",
    detail:
      "Client required a prominent commercial address on the Sector 70 main road with ground-floor retail and upper-floor office space. Architects Accord handled full architectural design, structural coordination, interior fit-out for all four floors, and custom reception and workstation furniture. Ground floor retail brand fit-out, first and second floor open-plan office with breakout zones, meeting rooms, and pantry. Signage and external facade cladding included in scope.",
    hero: "https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Reception design", "Open-plan workstations", "Meeting rooms", "Pantry & breakout", "Signage & facade"],
  },
  {
    id: "p03",
    code: "AA-2403",
    title: "3 BHK Apartment Interiors",
    type: "Residential",
    subType: "Interior Design",
    locality: "Sector 79, Mohali",
    plotSize: "—",
    builtUp: "1,820 Sq. Ft.",
    bedrooms: 3,
    bathrooms: 3,
    facing: "East",
    parking: 1,
    furnishing: "Full Interior Design",
    age: "Completed 2024",
    floor: "9 of 14",
    status: "Delivered",
    price: "Interior Design",
    pricePerSqft: "Residential Interiors",
    listingDate: "02 May 2024",
    rera: "AA-INT-2403",
    tags: ["Interiors", "High Floor", "Custom Furniture"],
    summary:
      "Complete interior design for a high-floor 3 BHK apartment — space planning, custom furniture, lighting, and material specification delivered by Architects Accord.",
    detail:
      "The client moved in with a bare-shell apartment and a clear brief: a warm, contemporary home with smart storage and no wasted space. Architects Accord designed a full interior scheme — false ceiling with cove lighting throughout, kitchen with handleless cabinets and integrated appliances, living and dining with custom TV unit and bookshelf, three bedrooms with wardrobes and study tables designed to the room. All loose furniture, curtains, and soft furnishings coordinated and supplied.",
    hero: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["False ceiling & lighting", "Modular kitchen", "Custom wardrobes", "Loose furniture", "Curtains & furnishings"],
  },
  {
    id: "p04",
    code: "AA-2404",
    title: "Residential Plot Construction",
    type: "Residential",
    subType: "Civil Engineering",
    locality: "Sector 88, JLPL Mohali",
    plotSize: "200 Sq. Yd.",
    builtUp: "3,400 Sq. Ft.",
    bedrooms: 4,
    bathrooms: 4,
    facing: "North",
    parking: 2,
    furnishing: "Semi-furnished",
    age: "Completed 2025",
    floor: "G + 2",
    status: "Delivered",
    price: "Architecture + Civil",
    pricePerSqft: "Full Construction",
    listingDate: "28 Feb 2025",
    rera: "AA-CIV-2404",
    tags: ["Civil Engineering", "Structural Design", "Construction Management"],
    summary:
      "Architecture, structural design, and full construction management for a 200 sq. yd. residential plot in JLPL Sector 88 — handled entirely by Architects Accord.",
    detail:
      "Client purchased a bare plot and engaged Architects Accord for the complete journey — from architectural design and municipal approvals through structural drawings, construction supervision, and handover. The project is a G+2 house with four bedrooms, a modular kitchen, double-height living room, and a terrace garden. Civil works were managed on-site with fortnightly client progress updates and photographic reports.",
    hero: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Municipal approvals", "Structural drawings", "Construction supervision", "Terrace garden", "Full handover"],
  },
  {
    id: "p05",
    code: "AA-2405",
    title: "Showroom Interior Design",
    type: "Commercial",
    subType: "Commercial Architecture",
    locality: "Aerocity, Mohali",
    plotSize: "300 Sq. Yd.",
    builtUp: "5,200 Sq. Ft.",
    bedrooms: null,
    bathrooms: 4,
    facing: "West",
    parking: "Front",
    furnishing: "Full Commercial Fit-out",
    age: "Completed 2024",
    floor: "G + 2",
    status: "Delivered",
    price: "Commercial Fit-out",
    pricePerSqft: "Showroom Grade",
    listingDate: "10 Mar 2024",
    rera: "AA-COM-2405",
    tags: ["Showroom", "Highway Facing", "Custom Display"],
    summary:
      "Showroom interior design and fit-out on the 200-ft Aerocity main artery — 45 ft. glass frontage, custom display fixtures, and lighting designed by Architects Accord.",
    detail:
      "A premium showroom brief for an automotive client on the Aerocity highway. The design challenge was to create an impactful, high-footfall retail environment across three floors with a 45-ft uninterrupted glass facade. Architects Accord designed the interior scheme — reception, display bays, mezzanine lounge, and service counter — and sourced all custom fixtures, lighting, and flooring. Full fit-out managed from material procurement through to handover.",
    hero: "https://images.unsplash.com/photo-1577412647305-991150c7d163?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["45 ft. glass facade", "Custom display fixtures", "Track lighting", "Mezzanine lounge", "Full fit-out"],
  },
  {
    id: "p06",
    code: "AA-2406",
    title: "2 BHK Renovation",
    type: "Residential",
    subType: "Renovations",
    locality: "Sector 67, Mohali",
    plotSize: "—",
    builtUp: "1,150 Sq. Ft.",
    bedrooms: 2,
    bathrooms: 2,
    facing: "South-West",
    parking: 1,
    furnishing: "Full Renovation",
    age: "Completed 2025",
    floor: "2 of 3",
    status: "Delivered",
    price: "Renovation",
    pricePerSqft: "Residential Renovation",
    listingDate: "05 Apr 2025",
    rera: "AA-REN-2406",
    tags: ["Renovation", "Kitchen Remodel", "Bathroom Upgrade"],
    summary:
      "Complete home renovation for a 2 BHK builder floor — kitchen remodel, bathroom upgrades, new flooring, and false ceiling throughout.",
    detail:
      "The client wanted their existing home transformed without moving out. Architects Accord phased the renovation to allow the family to stay in residence — completing the bedrooms and bathrooms first, then the living and kitchen. Works included full demolition and redo of both bathrooms with imported tiles and fittings, a new modular kitchen, false ceiling with LED lighting in all rooms, new vitrified tile flooring throughout, and painting. Project completed in 11 weeks.",
    hero: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Kitchen remodel", "Bathroom upgrade", "False ceiling & LED", "New flooring", "Full painting"],
  },
  {
    id: "p07",
    code: "AA-2407",
    title: "Custom Furniture Project",
    type: "Residential",
    subType: "Furniture Design & Supply",
    locality: "Sector 82, Mohali",
    plotSize: "—",
    builtUp: "2,400 Sq. Ft.",
    bedrooms: 3,
    bathrooms: null,
    facing: "East",
    parking: "—",
    furnishing: "Custom Furniture",
    age: "Completed 2024",
    floor: "G + 1",
    status: "Delivered",
    price: "Furniture Design",
    pricePerSqft: "Custom Joinery",
    listingDate: "17 Jan 2024",
    rera: "AA-FUR-2407",
    tags: ["Custom Furniture", "Joinery", "Bespoke Design"],
    summary:
      "Bespoke furniture design and supply for a 3 BHK home — custom wardrobes, kitchen cabinetry, TV units, study furniture, and a dining table designed to the room.",
    detail:
      "The client engaged Architects Accord specifically for custom furniture after completing their home with another contractor. The scope covered the full home: three bedroom wardrobes with internal fittings, modular kitchen with island, wall-to-wall bookshelf in the living room, custom TV unit with integrated storage, study table and wall shelf for the children's room, and a six-seater dining table in solid wood. All items were designed in-house, manufactured locally, and installed by the Architects Accord team.",
    hero: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Custom wardrobes", "Modular kitchen", "TV unit & storage", "Dining table", "Study furniture"],
  },
  {
    id: "p08",
    code: "AA-2408",
    title: "Penthouse Turnkey Project",
    type: "Residential",
    subType: "Turnkey Projects",
    locality: "Sector 66-A, Mohali",
    plotSize: "—",
    builtUp: "3,950 Sq. Ft.",
    bedrooms: 4,
    bathrooms: 5,
    facing: "North",
    parking: 2,
    furnishing: "Full Turnkey",
    age: "Completed 2025",
    floor: "12-13 of 13",
    status: "Delivered",
    price: "Turnkey Delivery",
    pricePerSqft: "Full Turnkey",
    listingDate: "19 Mar 2025",
    rera: "AA-TRN-2408",
    tags: ["Turnkey", "Penthouse", "Private Terrace"],
    summary:
      "End-to-end turnkey delivery for a top-floor duplex penthouse — architecture, interiors, custom furniture, smart home, and a 1,200 sq. ft. private terrace.",
    detail:
      "A full turnkey brief for a client relocating from Delhi. The penthouse spans the top two floors of a 13-storey building, with a 1,200 sq. ft. private terrace. Architects Accord handled the complete scope: interior architecture, false ceilings, kitchen and wardrobe design, furniture sourcing and supply, smart home wiring and control, terrace decking, pergola, and wet bar. The client handed over keys and received a move-in-ready home 14 months later.",
    hero: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Private terrace & pergola", "Smart home", "Custom furniture", "Wet bar", "Full turnkey handover"],
  },
];
